Replaced ls_npq_tsf_details with ls_npq_tsf_application_detail
DFE-Digital/teacher-cpd-dataform pull request #85
Opened 2024-05-29 10:22 UTC by AntPage1

Replaced ls_npq_tsf_details with ls_npq_tsf_application_detail which includes the updated logic relating to TSF eligibility criteria. This table is to be used in the NPQTSF Looker dashboard as well as 2 future Marts.

2024-05-29 16:05 UTC, consult1815 requested changes
I'm not sure we need two marts here as most of the code is identical. Do you think it would be possible to amalgamate the marts into one, with all the necessary checks, just omitting the WHERE statements and then add instructions in the table description  (and flag in field descriptions as well) on how to get the results of one of the two marts and then in Looker Studio add the requisite filters to get the desired output?

2024-05-30 08:52 UTC, AntPage1 commented on definitions/marts/looker_studio_marts/npq/ls_npq_tsf_application_detail.sqlx
> +      WHEN app.targeted_delivery_funding_eligibility = FALSE AND add.application_id IS NULL THEN ''
In the output Nathan requested that only the manually provided reason appears, previously I had 'Logic Unsatisfied'. The blank is used to identify those where the logic is satisfied and NULL is for any uncategorised rows which would require investigation to see why.

2024-05-30 08:53 UTC, AntPage1 commented on definitions/marts/looker_studio_marts/npq/ls_npq_tsf_application_detail.sqlx
> +      WHEN app.targeted_delivery_funding_eligibility = TRUE AND ex.application_id IS NULL THEN ''
In the output Nathan requested that only the manually provided reason appears, previously I had 'Logic Satisfied'. The blank is used to identify those where the logic is satisfied and NULL is for any uncategorised rows which would require investigation to see why.

2024-05-30 08:56 UTC, AntPage1 commented on definitions/marts/looker_studio_marts/npq/ls_npq_tsf_application_detail.sqlx
> +    ,CASE
Lines 144-148 create a column of 1s & 0s for is_included. Lines 150-154 create a column of the inclusion_reason. The conditions in both case statements are the same but the output differs. If there is a means of apply the logic for 2 outcomes without duplication I'm happy to change to that method.

2024-05-30 09:01 UTC, AntPage1 commented on definitions/marts/looker_studio_marts/npq/ls_npq_tsf_applications_to_review.sqlx
> +    tsf_primary_eligibility, -- Unused by the service as targeted_delivery_funding_eligibility also acts as the flag for this indicator. Included purely for visibility.
Marts will be combined into 1 and this document will be removed.

2024-05-30 09:01 UTC, AntPage1 commented on definitions/marts/looker_studio_marts/npq/ls_npq_tsf_applications_to_review.sqlx
> +    course_identifier NOT IN ('npq-early-headship-coaching-offer', 'npq-additional-support-offer') --EHCO/ASO courses are excluded as per instruction on 16/05/2024.
Marts will be combined into 1 and this document will be removed.

2024-05-30 10:31 UTC, consult1815 requested changes

2024-05-30 10:31 UTC, consult1815 commented on definitions/marts/looker_studio_marts/npq/ls_npq_tsf_application_detail.sqlx
>      },
I think we should cluster by cohort, you can see how to do that in the npq_enrolment code in dataform

2024-05-30 10:44 UTC, consult1815 approved these changes
Looks good

2024-05-30 10:44 UTC, merged